PACKAGE=csobclient
VENV=.venv

.PHONY: help
help:
	@echo "venv        -> prepare VENV with all dependencies installed"
	@echo "test        -> run tests"
	@echo "nox         -> run nox sessions"
	@echo "clean       -> remove autogenerated files (venv, cache, etc.)"
	@echo "coverage    -> run tests coverage and prepare HTML report"

.PHONY: venv
venv:
	python3 -m venv $(VENV)
	poetry install

.PHONY: test
test:
	poetry run pytest -svvv tests

.PHONY: nox
nox:
	nox

.PHONY: clean
clean:
	rm -rf $(VENV) build _build dist *.egg-info .coverage htmlcov
	find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
	py3clean . -v

.PHONY: coverage
coverage:
	poetry run pytest --cov-report html --cov=$(PACKAGE) tests/

.PHONY: lint
lint:
	poetry run pylint $(PACKAGE) tests
	poetry run pydocstyle --ignore=D102,D103,D105,D107,D203,D213 $(PACKAGE)/** tests/**
	poetry run black -l 79 . --check
